CMD /C ..\..\bpl-gen.bat g_slist_copy.c
CMD /C ..\..\bpl-gen.bat g_slist_find.c
CMD /C ..\..\bpl-gen.bat g_slist_free.c
CMD /C ..\..\bpl-gen.bat g_slist_index.c
CMD /C ..\..\bpl-gen.bat g_slist_insert.c
CMD /C ..\..\bpl-gen.bat g_slist_insert_before.c
CMD /C ..\..\bpl-gen.bat g_slist_insert_sorted.c
CMD /C ..\..\bpl-gen.bat g_slist_last.c
CMD /C ..\..\bpl-gen.bat g_slist_length.c
CMD /C ..\..\bpl-gen.bat g_slist_nth.c
CMD /C ..\..\bpl-gen.bat g_slist_nth_data.c
CMD /C ..\..\bpl-gen.bat g_slist_position.c
CMD /C ..\..\bpl-gen.bat g_slist_remove.c
CMD /C ..\..\bpl-gen.bat g_slist_remove_all.c
CMD /C ..\..\bpl-gen.bat g_slist_remove_link.c
CMD /C ..\..\bpl-gen.bat g_slist_reverse.c
