CMD /C ..\..\bpl-gen.bat sls_concat.c
CMD /C ..\..\bpl-gen.bat sls_copy.c
CMD /C ..\..\bpl-gen.bat sls_dispose.c
CMD /C ..\..\bpl-gen.bat sls_double_all.c
CMD /C ..\..\bpl-gen.bat sls_filter.c
CMD /C ..\..\bpl-gen.bat sls_insert.c
CMD /C ..\..\bpl-gen.bat sls_merge.c
CMD /C ..\..\bpl-gen.bat sls_remove.c
CMD /C ..\..\bpl-gen.bat sls_reverse.c
CMD /C ..\..\bpl-gen.bat sls_split.c
CMD /C ..\..\bpl-gen.bat sls_traverse.c
