CMD /C ..\bpl-gen.bat SLL-create.c
CMD /C ..\bpl-gen.bat SLL-delete-all.c
CMD /C ..\bpl-gen.bat SLL-delete.c
CMD /C ..\bpl-gen.bat SLL-filter.c
CMD /C ..\bpl-gen.bat SLL-find.c
CMD /C ..\bpl-gen.bat SLL-insert.c
CMD /C ..\bpl-gen.bat SLL-last.c
CMD /C ..\bpl-gen.bat SLL-merge.c
CMD /C ..\bpl-gen.bat SLL-reverse.c
