CMD /C ..\..\bpl-gen.bat g_list_find.c
CMD /C ..\..\bpl-gen.bat g_list_free.c
CMD /C ..\..\bpl-gen.bat g_list_index.c
CMD /C ..\..\bpl-gen.bat g_list_last.c
CMD /C ..\..\bpl-gen.bat g_list_length.c
CMD /C ..\..\bpl-gen.bat g_list_nth.c
CMD /C ..\..\bpl-gen.bat g_list_nth_data.c
CMD /C ..\..\bpl-gen.bat g_list_position.c
CMD /C ..\..\bpl-gen.bat g_list_reverse.c
